#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run unit tests for the action (workspace)
npm -w trigger-deployment run -s test || exit 1

# Build the action and stage dist output if changed (workspace)
npm -w trigger-deployment run -s build || exit 1

# Stage dist to ensure bundled action is committed
git add trigger-deployment/dist
